name: Push to Another Repo

on:
  push: 
    branches:
      - main  Educonnect

jobs:
  push_to_another_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2  # Checkout the source repository
        with:
          repository:https://github.com/raja170320/SIH-PROD.git
          ref: main  SIH-PROD

      - name: Set up Git
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"

      # Make changes to files (optional)
      # You can add additional steps to modify files if needed

      - name: Push changes to target repository
        run: |
          cd $GITHUB_WORKSPACE  # Change to the cloned repository directory
          git remote add target_repo username/target-repo.git  # Replace with the target repository URL
          git push target_repo HEAD:main  # Push changes to the target repository's main branch
